import json
import multiprocessing
from typing import Collection, Any
import http.client
from implementation import funsearch
from implementation import config
from implementation import sampler
from implementation import evaluator_accelerate
from implementation import evaluator
from implementation import code_manipulation
import admm_utils


class LLMAPI(sampler.LLM):
    """Language model that predicts continuation of provided source code.
    """

    def __init__(self, samples_per_prompt: int):
        super().__init__(samples_per_prompt)
        additional_prompt = ('Please modify the ADMM optimizer in the provided l1 function to incorporate an unfixed penalty parameter. Specifically, the penalty parameter rho should be adjusted dynamically during each iteration based on the current optimization state, rather than being fixed. Ensure that the updated rho is used correctly in the updates for X, Z, Y1, and Y2.'
                             'Only output the Python code, no descriptions.')
        self._additional_prompt = additional_prompt

    def draw_samples(self, prompt: str) -> Collection[str]:
        """Returns multiple predicted continuations of `prompt`."""
        return [self._draw_sample(prompt) for _ in range(self._samples_per_prompt)]

    def _draw_sample(self, content: str) -> str:
        prompt = '\n'.join([content, self._additional_prompt])
        while True:
            try:
                conn = http.client.HTTPSConnection("api.deepseek.com")

                payload = json.dumps({
                    "messages": [
                        {
                            "content": "You are a helpful programmer who is familar with python and Admm in optimization. ",
                            "role": "system"
                        },
                        {
                            "content": prompt,
                            "role": "user"
                        }
                    ],
                    "model": "deepseek-chat",
                    "frequency_penalty": 0,
                    "max_tokens": 2048,
                    "presence_penalty": 0,
                    "stop": None,
                    "stream": False,
                    "temperature": 0,
                    "top_p": 1,
                    "logprobs": False,
                    "top_logprobs": None
                })
                headers = {
                    'Authorization': 'Bearer sk-66575172e83e40b2bbcaa1cf6b9f0ae8',
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                }
                conn.request("POST", "/chat/completions", payload, headers)
                res = conn.getresponse()
                data = res.read().decode("utf-8")
                data = json.loads(data)
                print(data)
                response = data['choices'][0]['message']['content']
                return response
            except Exception:
                continue


class Sandbox(evaluator.Sandbox):
    """Sandbox for executing generated code. Implemented by RZ.

    RZ: Sandbox returns the 'score' of the program and:
    1) avoids the generated code to be harmful (accessing the internet, take up too much RAM).
    2) stops the execution of the code in time (avoid endless loop).
    """

    def __init__(self, verbose=False, numba_accelerate=False):
        """
        Args:
            verbose         : Print evaluate information.
            numba_accelerate: Use numba to accelerate the evaluation. It should be noted that not all numpy functions
                              support numba acceleration, such as np.piecewise().
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate

    def run(
            self,
            program: str,
            function_to_run: str,  # RZ: refers to the name of the function to run (e.g., 'evaluate')
            function_to_evolve: str,  # RZ: accelerate the code by decorating @numba.jit() on function_to_evolve.
            inputs: Any,  # refers to the dataset
            test_input: str,  # refers to the current instance
            timeout_seconds: int,
            **kwargs  # RZ: add this
    ) -> tuple[Any, bool]:
        """Returns `function_to_run(test_input)` and whether execution succeeded.

        RZ: If the generated code (generated by LLM) is executed successfully,
        the output of this function is the score of a given program.
        RZ: PLEASE NOTE THAT this SandBox is only designed for bin-packing problem.
        """
        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)
        if process.is_alive():
            # if the process is not finished in time, we consider the program illegal
            process.terminate()
            process.join()
            results = None, False
        else:
            if not result_queue.empty():
                results = result_queue.get_nowait()
            else:
                results = None, False

        if self._verbose:
            print(f'================= Evaluated Program =================')
            program_: code_manipulation.Program = code_manipulation.text_to_program(text=program)
            func_to_evolve_: str = kwargs.get('func_to_evolve', 'priority')
            function_: code_manipulation.Function = program_.get_function(func_to_evolve_)
            function_: str = str(function_).strip('\n')
            print(f'{function_}')
            print(f'-----------------------------------------------------')
            print(f'Score: {str(results)}')
            print(f'=====================================================')
            print(f'\n\n')

        return results

    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, dataset, numba_accelerate,
                                  result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            # compile the program, and maps the global func/var/class name to its address
            all_globals_namespace = {}
            # execute the program, map func/var/class to global namespace
            exec(program, all_globals_namespace)
            # get the pointer of 'function_to_run'
            function_to_run = all_globals_namespace[function_to_run]
            # return the execution results
            results = function_to_run(dataset)
            # the results must be int or float
            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
        except:
            # if raise any exception, we assume the execution failed
            result_queue.put((None, False))


specification = r'''
import numpy as np

def prox_l1(b, lambd):
    # The proximal operator of the l1 norm
    return np.maximum(0, b - lambd) + np.minimum(0, b + lambd)

@funsearch.evolve
def update_penalty(mu, rho, chgY, chgZ, chgX, opts):
    mu_update_factor = opts.get('mu_update_factor', 1.1)
    mu_decrease_factor = opts.get('mu_decrease_factor', 0.9)
    mu_min = opts.get('mu_min', 1e-4)
    mu_max = opts.get('mu_max', 1e4)

    # 基于残差的大小来更新 mu
    if np.max([chgY, chgZ, chgX]) < 0.1:  # 如果残差小，减小 mu
        mu = max(mu * mu_decrease_factor, mu_min)
    else:  # 如果残差大，增大 mu
        mu = min(mu * mu_update_factor, mu_max)

    return mu

def l1_standard(A, B, opts):
    tol = opts.get('tol', 1e-6)
    max_iter = opts.get('max_iter', 500)
    rho = opts.get('rho', 1.0)  # ADMM penalty parameter
    mu = opts.get('mu', 1e-4)  # 初始的惩罚因子
    DEBUG = opts.get('DEBUG', 0)

    d, na = A.shape
    _, nb = B.shape

    X = np.zeros((na, nb))
    Z = np.zeros_like(X)
    Y = np.zeros((d, nb))

    for iter in range(1, max_iter + 1):
        Xk = X.copy()
        Zk = Z.copy()

        # update X with proximal operator
        X = prox_l1(Z - (A.T @ Y / rho), 1 / rho)

        # update Z with a least squares solution
        Z = np.linalg.solve(A.T @ A + rho * np.eye(na), A.T @ (B - Y) + rho * X)

        # update the dual variable Y
        Y = Y + rho * (A @ Z - B)

        chgX = np.max(np.abs(Xk - X))
        chgZ = np.max(np.abs(Zk - Z))
        chgY = np.max(np.abs(A @ Z - B))

        # 更新惩罚因子 mu
        mu = update_penalty(mu, rho, chgY, chgZ, chgX, opts)

        if DEBUG and (iter == 1 or iter % 10 == 0):
            obj = np.linalg.norm(X.ravel(), 1)
            err = np.sqrt(chgY ** 2 + chgZ ** 2 + chgX ** 2)
            print(f'iter {iter}, rho={rho}, mu={mu}, obj={obj}, err={err}')

        if chgX < tol and chgZ < tol and chgY < tol:
            break

    obj = np.linalg.norm(X.ravel(), 1)
    err = np.sqrt(chgY ** 2 + chgZ ** 2 + chgX ** 2)

    return X, obj, err, iter

@funsearch.run
def evaluate(instances: dict) -> float:
    # 记录所有迭代次数
    all_iters = []

    for _ in range(10):  # 重复跑10次
        # 重新设置随机种子确保每次实例化时的随机性
        np.random.seed(None) 

        # Generate toy data
        d = instances['d']
        na = instances['na']
        nb = instances['nb']

        A = np.random.randn(d, na)
        X = np.random.randn(na, nb)
        B = A @ X
        b = B[:, 0]

        # Options for the l1 minimization
        opts = instances

        # Perform l1 minimization
        X2, obj, err, iter = l1_standard(A, B, opts)
        print(f'Iteration {iter}, Objective: {obj}, Error: {err}')
        
        # 记录每次运行的迭代次数
        all_iters.append(iter)

    # 返回10次运行的平均迭代次数
    avg_iter = np.mean(all_iters)
    print(f'Average Iterations over 10 runs: {avg_iter}')
    return -avg_iter
'''

# It should be noted that the if __name__ == '__main__' is required.
# Because the inner code uses multiprocess evaluation.
if __name__ == '__main__':
    class_config = config.ClassConfig(llm_class=LLMAPI, sandbox_class=Sandbox)
    config = config.Config(samples_per_prompt=4)
    admm_l1_config = admm_utils.datasets['l1']
    global_max_sample_num = 100
    # if it is set to None, funsearch will execute an endless loop
    funsearch.main(
        specification=specification,
        inputs=admm_l1_config,
        config=config,
        max_sample_nums=global_max_sample_num,
        class_config=class_config,
        log_dir='logs/sparse_models/l1/funsearch_l1',
        temperature=0
    )
